spring:
  data:
    redis:
      repositories:
        enabled: false

---
spring.config.activate.on-profile: local, test

---
spring.config.activate.on-profile: test

---
spring.config.activate.on-profile: dev

---
spring.config.activate.on-profile: qa

---
spring.config.activate.on-profile: prd